In [1]:
import networkx as nx
import csv
import pandas as pd
from itertools import product
import pandas as pd
import numpy as np
import random as rd
import matplotlib.pyplot as plt
G=nx.Graph()

In [2]:
import matplotlib.pyplot as plt
from networkx import *
import networkx as nx
import sys
# from __future__ import division, print_function

import numpy as np
import numpy.random as rand
import random as stdrand
import scipy.sparse as sparse
from numpy.linalg import norm, inv
import scipy.stats as stats

from datetime import datetime
from tqdm import trange

#from util import *
from viz import *

from matplotlib.backends.backend_pdf import PdfPages

In [3]:
def preprocessArgs(s, max_rounds):
    '''Argument processing common for most models.
    Returns:
        N, z, max_rounds
    '''

    N = np.size(s)
    max_rounds = int(max_rounds) + 1  # Round 0 contains the initial opinions
    z = s.copy()

    return N, z, max_rounds

def trustFunc(s, i, j, h):
    
    trust =  np.exp( - (s[i] - s[j])**2 / h )
    return trust


In [4]:
def deGroot(A, s, max_rounds, eps=1e-6, conv_stop=True, save=False):
    '''Simulates the DeGroot Model.
    Runs a maximum of max_rounds rounds of the DeGroot model. If the model
    converges sooner, the function returns.
    Args:
        A (NxN numpy array): Adjacency matrix
        s (1xN numpy array): Initial opinions vector
        max_rounds (int): Maximum number of rounds to simulate
        eps (double): Maximum difference between rounds before we assume that
        the model has converged (default: 1e-6)
        conv_stop (bool): Stop the simulation if the model has converged
        (default: True)
        save (bool): Save the simulation data into text files
    Returns:
        A txN vector of the opinions of the nodes over time
    '''

    N, z, max_rounds = preprocessArgs(s, max_rounds)

    opinions = np.zeros((max_rounds, N))
    print(opinions)
    opinions[0, :] = s

    for t in trange(1, max_rounds):

        z = A.dot(z)


        opinions[t, :] = z

        # print z

        # print norm(opinions[t - 1, :] - opinions[t, :], np.inf)
        if conv_stop and \
           norm(opinions[t - 1, :] - opinions[t, :], np.inf) < eps:
            print('DeGroot converged after {t} rounds'.format(t=t))
            break

    if save:
        timeStr = datetime.now().strftime("%m%d%H%M")
        simid = 'dg' + timeStr
#         save_data(simid, N=N, max_rounds=max_rounds, eps=eps,
#                       rounds_run=t+1, A=A, s=s,
#                       opinions=opinions[0:t+1, :])

    return opinions[0:t+1, :]



In [5]:
import csv
import pandas as pd
from itertools import product
import pandas as pd
import numpy as np
import random as rd
import matplotlib.pyplot as plt
import csv
#import igraph as ig
import networkx as nx
from textblob import TextBlob
import pandas as pd
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

pd.options.display.max_rows = 999
data_follower=pd.read_csv('/home/shuham/Desktop/Projects/NSW/NSW_Kashmir/#Kashmir_follower_followee_network.csv')
data_tweet= pd.read_csv('/home/shuham/Desktop/Projects/NSW/NSW_Kashmir/#Kashmir_tweets.csv')

In [6]:
data_tweet.columns

Index(['user_id', 'status_id', 'created_at', 'screen_name', 'text', 'source',
       'display_text_width', 'reply_to_status_id', 'reply_to_user_id',
       'reply_to_screen_name', 'is_quote', 'is_retweet', 'favorite_count',
       'retweet_count', 'hashtags', 'symbols', 'urls_url', 'urls_t.co',
       'urls_expanded_url', 'media_url', 'media_t.co', 'media_expanded_url',
       'media_type', 'ext_media_url', 'ext_media_t.co',
       'ext_media_expanded_url', 'ext_media_type', 'mentions_user_id',
       'mentions_screen_name', 'lang', 'quoted_status_id', 'quoted_text',
       'quoted_created_at', 'quoted_source', 'quoted_favorite_count',
       'quoted_retweet_count', 'quoted_user_id', 'quoted_screen_name',
       'quoted_name', 'quoted_followers_count', 'quoted_friends_count',
       'quoted_statuses_count', 'quoted_location', 'quoted_description',
       'quoted_verified', 'retweet_status_id', 'retweet_text',
       'retweet_created_at', 'retweet_source', 'retweet_favorite_count',
    

In [7]:
comment_words = ' ' #We will be appending the words to this var
stopwords = set(STOPWORDS) #Finds all stop words in the set of tweets.
for val in data_tweet.text:
   val = str(val) #convert all tweet content into strings
   tokens = val.split() #Split all strings into individual components
   for i in range(len(tokens)):
      tokens[i] = tokens[i].lower() #Converts all the individual strings to lower case.
for words in tokens:
   comment_words = comment_words + words + ' '

In [8]:
polarity = []
for val in data_tweet.index:
    sentiments = TextBlob(data_tweet['text'][val])
    polarity.append(sentiments.polarity)

In [9]:
polarity

[-0.125,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.1346153846153846,
 0.0,
 -0.053571428571428575,
 0.0,
 0.0,
 0.0,
 0.1275,
 0.0,
 0.0,
 0.0,
 0.0,
 -0.2,
 -0.015909090909090914,
 0.0,
 -0.2,
 0.0,
 0.14285714285714285,
 -0.5,
 0.0,
 -0.375,
 0.0,
 6.938893903907228e-18,
 0.03571428571428571,
 0.0,
 -0.09999999999999999,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 -0.25,
 -0.016666666666666666,
 0.34,
 0.0,
 0.0,
 0.0,
 -0.29791666666666666,
 0.0,
 0.85,
 0.0,
 0.0,
 0.0,
 0.0,
 -0.09999999999999998,
 0.0,
 0.0,
 0.07500000000000001,
 0.35,
 0.0,
 0.0,
 0.34,
 0.85,
 -0.125,
 0.0,
 0.35,
 0.0,
 -0.07777777777777779,
 -0.15111111111111114,
 0.20000000000000004,
 0.0,
 0.1396103896103896,
 0.0035714285714285657,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.09523809523809523,
 0.0,
 0.0,
 -0.14166666666666664,
 0.35,
 0.07047619047619047,
 0.35,
 0.0,
 0.05555555555555555,
 0.09285714285714286,
 0.4,
 0.07500000000000001,
 0.0,
 0.5,
 0.1396103896103896,
 0.0,
 -0.6999999999999998,
 0.0,
 0.0,
 -0.0999

In [10]:
G = nx.read_edgelist('retweet_kashmir.csv', delimiter=',', nodetype=str, data=[('Source',str),('Target',str)])

print (nx.info(G))

Name: 
Type: Graph
Number of nodes: 184
Number of edges: 145
Average degree:   1.5761


In [11]:
A=nx.adjacency_matrix(G)

In [12]:
A.shape

(184, 184)

In [13]:
print(A)

  (0, 1)	1
  (1, 0)	1
  (1, 5)	1
  (1, 26)	1
  (1, 32)	1
  (1, 45)	1
  (1, 47)	1
  (1, 94)	1
  (1, 119)	1
  (2, 3)	1
  (2, 4)	1
  (3, 2)	1
  (4, 2)	1
  (4, 56)	1
  (4, 108)	1
  (5, 1)	1
  (6, 7)	1
  (6, 8)	1
  (7, 6)	1
  (8, 6)	1
  (9, 10)	1
  (10, 9)	1
  (10, 13)	1
  (10, 92)	1
  (10, 107)	1
  :	:
  (159, 158)	1
  (160, 161)	1
  (161, 160)	1
  (162, 163)	1
  (163, 162)	1
  (164, 16)	1
  (165, 34)	1
  (166, 18)	1
  (167, 168)	1
  (168, 167)	1
  (169, 170)	1
  (170, 169)	1
  (171, 16)	1
  (172, 75)	1
  (173, 69)	1
  (174, 100)	1
  (175, 18)	1
  (176, 30)	1
  (177, 178)	1
  (178, 177)	1
  (179, 16)	1
  (180, 30)	1
  (181, 182)	1
  (182, 181)	1
  (183, 73)	1


In [14]:
def stochastic_matrix(A):
    return A/A.sum(axis=1)

In [15]:
A=stochastic_matrix(A)
A = np.squeeze(np.asarray(A))

In [16]:
s=np.random.normal(0.5,0.3,184)

In [17]:
s=np.asarray(polarity)
s=s[0:184,]
s

array([-1.25000000e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.34615385e-01,  0.00000000e+00,
       -5.35714286e-02,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.27500000e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -2.00000000e-01, -1.59090909e-02,  0.00000000e+00,
       -2.00000000e-01,  0.00000000e+00,  1.42857143e-01, -5.00000000e-01,
        0.00000000e+00, -3.75000000e-01,  0.00000000e+00,  6.93889390e-18,
        3.57142857e-02,  0.00000000e+00, -1.00000000e-01,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -2.50000000e-01,
       -1.66666667e-02,  3.40000000e-01,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -2.97916667e-01,  0.00000000e+00,  8.50000000e-01,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -1.00000000e-01,  

In [18]:
#s=np.delete(s,199)
s.shape

(184,)

In [19]:
max_rounds=500
opinionsIterations=deGroot(A, s, max_rounds, eps=1e-6, conv_stop=True, save=True)
print(opinionsIterations[499])
#plot_opinions(opinionsIterations, title='', dcolor=False, interp=True,cmap=plt.cm.cool, linewidth=1.0)

100%|██████████| 500/500 [00:00<00:00, 7640.18it/s]

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[ 0.          0.05338542  0.015       0.21        0.21        0.
 -0.02678571  0.13461538  0.13461538 -0.03526187 -0.03513099  0.
 -0.03517316 -0.03521826 -0.03521924  0.         -0.01978175 -0.01590909
 -0.01464286 -0.03528627 -0.03510685 -0.03528627 -0.5         0.04761905
 -0.23148148  0.          0.         -0.5        -0.05       -0.00535714
 -0.00535714 -0.00535714  0.          0.          0.00902199  0.
  0.00902199  0.          0.         -0.01666667 -0.125       0.
  0.34        0.          0.          0.          0.          0.
  0.          0.         -0.01590909 -0.1         0.175       0.
  0.          0.21        0.015      -0.03529999 -0.03509328  0.85
  0.34       -0.01590909  0.         -0.1        -0.07777778  0.
  0.          0.          0.13961039 -0.01145833  0.         -0.04821429
  0.          0.00902199 -0.03